--Active customers at a date
SELECT 'PPDCNT' DESCR,COUNT(*) total_count
FROM F1_SVC_TASK A, F1_SVC_TASK_REL_OBJ B, CI_SA C,
CI_SA_SP D, D1_SP_IDENTIFIER E, D1_INSTALL_EVT F, D1_DVC_CFG G, D1_DVC_IDENTIFIER H
WHERE TRIM(A.BUS_OBJ_CD)='CmPrepayBillerTaskDPDC'
AND A.F1_SVC_TASK_ID = B.F1_SVC_TASK_ID
AND TRIM(B.MAINT_OBJ_CD) = 'ACCOUNT'
AND B.PK_VALUE1 = C.ACCT_ID
AND C.SA_ID = D.SA_ID and c.start_dt<'2024-12-15'
AND C.SA_TYPE_CD = 'PPD'   --,'POPD')
AND D.SP_ID = E.ID_VALUE
AND E.SP_ID_TYPE_FLG = 'D1EI'
AND E.D1_SP_ID = F.D1_SP_ID
AND F.DEVICE_CONFIG_ID = G.DEVICE_CONFIG_ID
AND F.D1_REMOVAL_DTTM IS NULL
AND G.D1_DEVICE_ID = H.D1_DEVICE_ID
AND H.DVC_ID_TYPE_FLG = 'D1SN'
AND LENGTH(H.ID_VALUE) = 8