SELECT 
    DI.ID_VALUE AS DEVICE_ID,
    MAX(ms.MSRMT_DTTM) AS MAX_KWH_READ_DATE,
    --MAX(ms.MSRMT_VAL) KEEP (DENSE_RANK LAST ORDER BY ms.MSRMT_DTTM) AS LAST_KWH_VALUE,
    SUM(ms.MSRMT_VAL) AS TOTAL_KWH_READING
FROM 
    d1_dvc_cfg DC
JOIN 
    d1_dvc_identifier DI ON DC.D1_DEVICE_ID = DI.D1_DEVICE_ID
JOIN 
    d1_measr_comp MC ON DC.DEVICE_CONFIG_ID = MC.DEVICE_CONFIG_ID
JOIN 
    d1_measr_comp_identifier MI ON MC.MEASR_COMP_ID = MI.MEASR_COMP_ID
JOIN 
    d1_msrmt ms ON MI.MEASR_COMP_ID = ms.MEASR_COMP_ID
WHERE 
    DI.DVC_ID_TYPE_FLG = 'D1SN'
    --AND DI.ID_VALUE IN ('90134355')
    AND MI.ID_VALUE = 'kWh Daily'
GROUP BY 
    DI.ID_VALUE