SELECT N.ADHOC_CHAR_VAL OLD_CONSUMER_ID,sum(CALC_AMT) AMOUNT, sum(END_MSRMT-START_MSRMT) CONSUMPTION, to_char(A.START_DT, 'Mon-rr') MONTH

FROM CISADM.CI_BSEG A,CISADM.CI_BSEG_CALC B,CISADM.C1_USAGE X,CISADM.D1_USAGE Y ,CISADM.D1_USAGE_SCALAR_DTL Z,CISADM.CI_SA L,CISADM.CI_SA_SP M,CISADM.CI_SP_CHAR N 
WHERE
  A.SA_ID=L.SA_ID AND L.SA_ID=M.SA_ID AND M.SP_ID=N.SP_ID AND A.BSEG_ID=B.BSEG_ID AND BSEG_STAT_FLG='50'AND A.BSEG_ID=X.BSEG_ID AND
X.USAGE_ID=Y.USG_EXT_ID AND Y.D1_USAGE_ID=Z.D1_USAGE_ID AND N.CHAR_TYPE_CD='CM_LEGCY' 
AND D1_FINAL_UOM_CD='KWH'
AND D1_FINAL_TOU_CD NOT IN ('OFF','ON')
AND A.END_DT <= :F2
and N.ADHOC_CHAR_VAL = '29538972'
group by N.ADHOC_CHAR_VAL, to_char(A.START_DT, 'Mon-rr')
 ORDER BY to_date(to_char(A.START_DT, 'Mon-rr'), 'Mon-rr')